language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "pypy"
install: 
 - sudo apt-get install zlib1g zlib1g-dev
 - sudo ln -s /usr/lib/i386-linux-gnu/libz.so /usr/lib/
 - pip install PIL --use-mirrors ; true
script: tests/alltests.py
